services:
  nexus:
    image: sonatype/nexus3:3.69.0
    restart: unless-stopped
    ports:
      - 8083:8081
      - 8089:8888
    environment:
      - "NEXUS_CONTEXT=repository"
    volumes:
      - ./data/nexus-data:/nexus-data
  nexus_aoc:
    image: sonatype/nexus3:3.72.0
    restart: unless-stopped
    ports:
      - 9083:8081
      - 9089:8888
    volumes:
      - ./data/nexus-data-aoc:/nexus-data
  zrok_repo:
      image: openziti/zrok
      restart: unless-stopped
      user: "1001"
      volumes:
        - ${HOME}/.zrok:/.zrok
      environment:
          HOME: "/"
          PFXLOG_NO_JSON: "true"
      command: share reserved "aocrepo" --headless
      links:
        - nexus_aoc
  zrok_registry:
      image: openziti/zrok
      restart: unless-stopped
      user: "1001"
      volumes:
        - ${HOME}/.zrok:/.zrok
      environment:
          HOME: "/"
          PFXLOG_NO_JSON: "true"
      command: share reserved "aoccr" --headless
      links:
        - nexus_aoc
  registry_frontend_lcas:
    image: klausmeyer/docker-registry-browser:latest
    environment:
      - 'DOCKER_REGISTRY_URL=http://nexus:8888'
      - PUBLIC_REGISTRY_URL=lcas.lincoln.ac.uk
      - 'SECRET_KEY_BASE=/AtOvCMBJedRBX+g'
      - ENABLE_COLLAPSE_NAMESPACES=true
      - ENABLE_DELETE_IMAGES=false
      - SCRIPT_NAME=/docker-images
      - RAILS_RELATIVE_URL_ROOT=/docker-images

    ports:
      - '9080:8080'
    links:
      - nexus
