version: '3.3'

services:
  nexus:
    image: sonatype/nexus3:3.69.0
    restart: always
    ports:
      - 8083:8081
      - 8089:8888
    environment:
      - "NEXUS_CONTEXT=repository"
    volumes:
      - ./data/nexus-data:/nexus-data
  # registry-own:
  #   container_name: registry
  #   restart: always
  #   image: registry
  #   ports:
  #     - 8081:5000
  #   volumes:
  #     - ./config/config.yml:/etc/docker/registry/config.yml:ro
  #     - /vol/owncloud/REGISTRY_DATA/registry-own:/var/lib/registry:rw
  #   #environment:
  #     #- "STANDALONE=true"
  #     #- "MIRROR_SOURCE=https://registry-1.docker.io"
  #     #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
  # registry-cache:
  #   container_name: registry-cache
  #   restart: always
  #   image: registry
  #   ports:
  #     - 8082:5000
  #   volumes:
  #     - ./config/config-cache.yml:/etc/docker/registry/config.yml:ro
  #     - /vol/owncloud/REGISTRY_DATA/registry-cache:/var/lib/registry:rw
  #   #environment:
  #     #- "STANDALONE=true"
  #     #- "MIRROR_SOURCE=https://registry-1.docker.io"
  #     #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
  # registry-frontend:
  #   container_name: registry-frontend
  #   restart: always
  #   image: konradkleine/docker-registry-frontend:v2
  #   ports:
  #     - 8088:80
  #   # volumes:
  #   #   - ./config/config-cache.yml:/etc/docker/registry/config.yml:ro
  #   #   - /vol/owncloud/REGISTRY_DATA/registry-cache:/var/lib/registry:rw
  #   links:
  #     - registry-own
  #   environment:
  #     - "ENV_DOCKER_REGISTRY_HOST=registry-own"
  #     - "ENV_DOCKER_REGISTRY_PORT=5000"
  #     - "ENV_REGISTRY_PROXY_FQDN=lcas.lincoln.ac.uk"
  #     - "ENV_REGISTRY_PROXY_PORT=443"
  #     - "ENV_MODE_BROWSE_ONLY=false"
  #     #- "STANDALONE=true"
  #     #- "MIRROR_SOURCE=https://registry-1.docker.io"
  #     #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
