services:
  nexus:
    image: sonatype/nexus3:3.69.0
    restart: always
    ports:
      - 8083:8081
      - 8089:8888
    environment:
      - "NEXUS_CONTEXT=repository"
    volumes:
      - ./data/nexus-data:/nexus-data
  nexus_aoc:
    image: sonatype/nexus3:3.72.0
    restart: always
    ports:
      - 9083:8081
      - 9089:8888
    volumes:
      - ./data/nexus-data-aoc:/nexus-data
